server:
  port: 8081

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**   # Matches exactly controller path
          # No StripPrefix

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**

        - id: post-service
          uri: lb://post-service
          predicates:
            - Path=/posts/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
