server:
  port: 8081

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
            - StripPrefix=1   # removes "/api"
            

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**

        - id: post-service
          uri: lb://post-service
          predicates:
            - Path=/api/post/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.config: DEBUG
    org.springframework.boot.context.config: DEBUG


management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway


