server:
  port: 8081

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        # Auth Service
        - id: auth-service
          uri: lb://auth-service   # 'lb://' means load-balanced via Eureka
          predicates:
            - Path=/api/auth/**        # All requests starting with /auth
          # filters:
            # - StripPrefix=1        # Removes /auth before forwarding

        # User Service
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          # filters:
            # - StripPrefix=1

        # Post Service
        - id: post-service
          uri: lb://post-service
          predicates:
            - Path=/api/posts/**
          # filters:
            # - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.config: DEBUG
    org.springframework.boot.context.config: DEBUG
