server:
  port: 9100
  servlet:
    context-path: /api

spring:
  application:
    name: notification-service

  data:
    mongodb:
      host: localhost
      port: 27017
      database: notification-db

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      mail-group:
        group-id: mail-consumer-group
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        properties:
          spring.json.trusted-packages: "*"
      web-group:
        group-id: web-consumer-group
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        properties:
          spring.json.trusted-packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    admin:
      auto-create: true
    topic:
      mail: mail-notification
      web: web-notification

  mail:
    host: smtp.gmail.com
    port: 587
    username: noreplyprojectmt@gmail.com
    password: 'rgkq aasa zfrp tvpv'
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.debug: true

jwt:
  refresh:
    secret: YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXphYmNkZWYx
    expiration: 86400000   # 1 day in ms
  access:
    secret: der5tghjiolo987ytgvcdswerdfgyu76t54e345rtyu8ijnbgtrdsxcdfew2
    expiration: 3600000     # 1 hour in ms

app:
  frontend-url: http://localhost:3000
  forgot-password-web-url: http://localhost:3000/forgot-password
