server:
  port: 8084
  servlet:
    context-path: /api

spring:
  application:
    name: post-service

  data:
    mongodb:
      host: localhost
      port: 27017
      database: post-db

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    admin:
      auto-create: true
    topic:
      web: web-notification

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

resilience4j:
  circuitbreaker:
    instances:
      userService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

  retry:
    instances:
      authServiceRetry:
        max-attempts: 3                # Total attempts (1 initial + 2 retries)
        wait-duration: 2s              # Delay between retries
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        max-wait-duration: 10s

  ratelimiter:
    instances:
      authServiceRateLimiter:
        limit-for-period: 5            # Max calls per refresh period
        limit-refresh-period: 1s       # Refresh period
        timeout-duration: 0            # Wait time if limit exceeded

management:
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    env:
      enabled: true   # lets environment variables show up

info:
  app:
    name: post-service
    description: User Post management service
    version: 1.0.0
  author: Sanket Pawar


